# Generated by Django 4.2.5 on 2023-09-26 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('badges', models.IntegerField(verbose_name='Badges Won')),
                ('is_gym_leader', models.BooleanField(default=False, verbose_name='Gym Leader')),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokedex_number', models.IntegerField(verbose_name='Pokedex Number')),
                ('name', models.CharField(max_length=30)),
                ('nickname', models.CharField(default='', max_length=30)),
                ('poke_type', models.CharField(default='', max_length=50, verbose_name='Pokemon Type')),
                ('types', models.JSONField("Types(JSON)")),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.trainer')),
            ],
        ),
    ]
