# Generated by Django 4.2.5 on 2023-09-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_pokemon_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='poke_type',
            new_name='type',
        ),
    ]
