# Generated by Django 4.2.5 on 2023-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pokemon_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('power_point', models.IntegerField(verbose_name='PP')),
                ('power', models.IntegerField()),
                ('accuracy', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='moves',
            field=models.ManyToManyField(to='main_app.move'),
        ),
    ]
